language: python
sudo: false
cache: pip

matrix:
  include:
      - python: 2.7
        env: TOX_ENV=py27
      - python: 3.3
        env: TOX_ENV=py33
      - python: 3.5
        env: TOX_ENV=py35
      - python: pypy
        env: TOX_ENV=pypy
install:
  - pip install tox==2.0.2
script:
  - tox -e $TOX_ENV
